print("Poniedziałek")
print("Wtorek", end="\t")
print("Ś\nroda")
print("1", "2", "3", "4", "5", "6")
print("1", "2", "3", "4", "5", "6", sep="*")
print("1", "2", "3", "4", "5", "6", sep="")
print("Kolejka", sep="-")
print("K","o","l","e","j","k","a", sep="-")
print("K"+"o"+"l"+"e"+"j"+"k"+"a", sep="-")
print("ko"*10)
print("#","F"*6, sep="")
print("#"+"F"*6)
print(("#"+"F")*6)
